name: Deploy with Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Production

    env: 
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Confirm VERCEL_TOKEN is set
        run: |
          echo ${{ secrets.VERCEL_TOKEN }}
          echo ${{ vars.DATABASE_URL }} 

        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel deploy --prod --token $VERCEL_TOKEN --yes
