name: Deploy with Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: 
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Confirm VERCEL_TOKEN is set
        run: echo $VERCEL_TOKEN

        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: npm install

      - name: Install Drizzle
        run: npm i -g drizzle-kit

      - name: Generate migrations
        run: npm run db:generate

      - name: Run migrations
        run: npm run db:migrate

      - name: Deploy to Vercel
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel deploy --prod --token $VERCEL_TOKEN