name: Deploy with Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate migrations
        run: npx drizzle-kit generate

      - name: Run migrations
        run: npx drizzle-kit migrate

      - name: Deploy to Vercel
        run: npx vercel deploy --prod
