name: Deploy with Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bun install

      - name: Install Drizzle
        run: bun i -g drizzle-kit

      - name: Generate migrations
        run: drizzle-kit generate

      - name: Run migrations
        run: drizzle-kit migrate

      - name: Deploy to Vercel
        run: npx vercel deploy --prod
